title: Allagi.ai
author: ""
email: connect@allagi.ai
description: Enabling affordable and accessible precision oncology with AI
baseurl: ""
url: https://allagi.ai


# Build settings
theme: minima
plugins:
  - jekyll-feed
